# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_read_item_items_item_id_get(self):
        """Test case for read_item_items_item_id_get

        Read Item  # noqa: E501
        """
        pass

    def test_read_root_get(self):
        """Test case for read_root_get

        Read Root  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
