# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from .import rpc_responses_grpc_def_pb2 as rpc__responses__grpc__def__pb2


class ResponseCallsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_users = channel.unary_unary(
                '/rpc.ResponseCalls/get_users',
                request_serializer=rpc__responses__grpc__def__pb2.EmptyRequest.SerializeToString,
                response_deserializer=rpc__responses__grpc__def__pb2.GetUsersResponse.FromString,
                )


class ResponseCallsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_users(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResponseCallsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_users': grpc.unary_unary_rpc_method_handler(
                    servicer.get_users,
                    request_deserializer=rpc__responses__grpc__def__pb2.EmptyRequest.FromString,
                    response_serializer=rpc__responses__grpc__def__pb2.GetUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rpc.ResponseCalls', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ResponseCalls(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_users(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpc.ResponseCalls/get_users',
            rpc__responses__grpc__def__pb2.EmptyRequest.SerializeToString,
            rpc__responses__grpc__def__pb2.GetUsersResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
